name: checks
on:
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@tnezdev'
          cache: 'pnpm'
      - name: Installing Dependencies
        run: pnpm install --frozen-lockfile
      - name: Running Code Checks
        run: pnpm turbo check:*
      - name: Running Tests
        run: pnpm turbo test
      - name: Require Changeset
        run: pnpm run require-changeset
