name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Installing Dependencies
        run: npm ci
      - name: Checking Code Style
        run: npm run checks:code-style
      - name: Checking Static Types
        run: npm run checks:types
      - name: Running Unit Tests
        run: npm test
      - name: Transpiling Code
        run: npm run build
