name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@tnezdev'
      - name: Installing Dependencies
        run: npm ci
      - name: Checking Code Style
        run: npm run checks:code-style
      - name: Checking Static Types
        run: npm run checks:types
      - name: Running Unit Tests
        run: npm test
      - name: Transpiling Code
        run: npm run build
      - name: Publishing Code
        uses: JS-DevTools/npm-publish@v1
        with:
          access: 'public'
          token: ${{ secrets.NPM_TOKEN }}
